name: test glTF Transform
on: [push]
jobs:
    gather-testing-data:
        runs-on: ubuntu-latest
        steps:
            - run: git clone https://github.com/KhronosGroup/glTF-Sample-Assets.git
            - name: Cache for testing
              id: asset-cache
              uses: actions/cache@v3
              with:
                path:  ~/glTF-Sample-Assets
                key: ${{ runner.os }}-assets

    test-transform:
        needs: gather-testing-data
        strategy:
            fail-fast: true
            max-parallel: 2
            matrix:
                transform: ['draco', 'optimize']
                models: ['AlphaBlendModeTest', 'AnimatedMorphCube']
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repo"
              uses: actions/checkout@v4
            - name: Get assets
              if: needs.gather-testing-data.outputs.cache-hit != 'true'
              run: git clone https://github.com/KhronosGroup/glTF-Sample-Assets.git
            - name: "Setup NodeJS"
              uses: actions/setup-node@v4
            - name: "Install glTF-transform"
              run: npm install --global @gltf-transform/cli
            - name: "Apply transform"
              run: gltf-transform ${{ matrix.transform }} glTF-Sample-Assets/Models/${{ matrix.models }}/glTF-Binary/${{ matrix.models }}.glb output.glb
            - name: "Inspect data"
              id: data 
              run: |
                gltf-transform inspect output.glb --format csv > output-data.txt
                gltf-transform inspect glTF-Sample-Assets/Models/${{ matrix.models }}/glTF-Binary/${{ matrix.models }}.glb --format csv > input-data.txt
                echo "Testing ${{ matrix.transform }} on ${{matrix.models}}" > testing-${{ matrix.transform }}-${{matrix.models}}.txt
                python parseData.py input-data.txt output-data.txt >> testing-${{ matrix.transform }}-${{matrix.models}}.txt
            - name: "Publish results"
              uses: actions/upload-artifact@v4
              with:
                name: Test-${{ matrix.transform }}-${{matrix.models}}
                path: testing-*.txt
    