name: test glTF Transform
on: [push]
jobs:
    gather-testing-data:
        runs-on: ubuntu-latest
        steps:
            - run: git clone https://github.com/KhronosGroup/glTF-Sample-Assets.git
            - name: Cache for testing
              id: asset-cache
              uses: actions/cache@v3
              with:
                path:  ~/glTF-Sample-Assets
                key: ${{ runner.os }}-assets

    test-transform:
        needs: gather-testing-data
        strategy:
            fail-fast: true
            max-parallel: 2
            matrix:
                transform: ['draco', 'optimize']
                models: ['AlphaBlendModeTest/glTF-Binary/AlphaBlendModeTest.glb', 'AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb']
        runs-on: ubuntu-latest
        steps:
            - name: Get assets
              if: needs.gather-testing-data.outputs.cache-hit != 'true'
              run: git clone https://github.com/KhronosGroup/glTF-Sample-Assets.git
            - name: "Setup NodeJS"
              uses: actions/setup-node@v4
            - name: "Install glTF-transform"
              run: npm install --global @gltf-transform/cli
            - name: "Apply transform"
              run: gltf-transform ${{ matrix.transform }} glTF-Sample-Assets/Models/${{ matrix.models }} output.glb
            - name: "Inspect data"
              run: diff `gltf-transform inspect output.glb` `glTF-Sample-Assets/Models/${{ matrix.models }}`
 
    